# Generated by Django 6.0.6 on 2026-06-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('range_min', models.IntegerField()),
                ('range_max', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('charging_time', models.IntegerField()),
                ('playload', models.IntegerField()),
                ('gps', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.category')),
                ('colours', models.ManyToManyField(to='mercury.color')),
            ],
        ),
    ]
