# Generated by Django 4.2.30 on 2026-07-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0002_remove_product_quantity_alter_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
